<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Utility\BuildingBlocks.Utility.csproj" />
    <ProjectReference Include="..\..\Catalog\Nursery.Catalog.Application\Nursery.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\Catalog\Nursery.Catalog.Infrastructure\Nursery.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Nursery.Orders.Domain\Nursery.Orders.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\UpdateOrder\" />
  </ItemGroup>

</Project>
