<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b61e8bea-a143-4e5f-b5ab-a93b20f13a9f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Views\Home\" />
    <Folder Include="wwwroot\Images\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
