<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.5" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\..\Catalog\Nursery.Catalog.Domain\Nursery.Catalog.Domain.csproj" />
    <ProjectReference Include="..\Nursery.Catalog.Application\Nursery.Catalog.Application.csproj" />
  </ItemGroup>

</Project>
