<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Utility\BuildingBlocks.Utility.csproj" />
    <ProjectReference Include="..\Nursery.Orders.Infrastructure\Nursery.Orders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
