<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6b2f89f7-0514-421b-b765-456d589d0577</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.19.1-beta.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.19.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />
    <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\BuildingBlocks.Common\BuildingBlocks.Common.csproj" />
    <ProjectReference Include="..\Modules\Payment\Nursery.Payment.Api\Nursery.Payment.Api.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Nursery.Catalog.Api\Nursery.Catalog.Api.csproj" />
    <ProjectReference Include="..\Modules\Customer\Customer.API\Customer.API.csproj" />
    <ProjectReference Include="..\Modules\Identity\Nursery.Identity\Nursery.Identity.csproj" />
    <ProjectReference Include="..\Modules\Orders\Nursery.Orders.API\Nursery.Orders.API.csproj" />
    <ProjectReference Include="..\Modules\Shippings\Nursery.Shippings.API\Nursery.Shippings.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="plant\images\nursery\uploads\" />
  </ItemGroup>

</Project>
