<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6b2f89f7-0514-421b-b765-456d589d0577</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Catalog\Nursery.Catalog.Api\Nursery.Catalog.Api.csproj" />
    <ProjectReference Include="..\Modules\Customer\Customer.API\Customer.API.csproj" />
    <ProjectReference Include="..\Modules\Identity\Nursery.Identity\Nursery.Identity.csproj" />
    <ProjectReference Include="..\Modules\Orders\Nursery.Orders.API\Nursery.Orders.API.csproj" />
  </ItemGroup>

</Project>
